apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: knative-foundations-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: InMemoryChannel
    name: basic-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-display
