# Apache Camel Source "Hello World"
#
# Full documentation and other examples at: https://knative.dev/docs/eventing/samples/apache-camel-source/
#
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-timer-source
spec:
  source:
    flow:
      from:
        uri: timer:tick
        parameters:
          period: 3s
        steps:
          - set-header:
              name: Content-Type
              constant: text/plain
          - set-body:
              constant: Hello world!
  sink:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-display
